### ISSUE TITLE
Add argument to commit changelog changes in `changelog -r`

### ISSUE THREAD

**Issue by boissonnat** [mathieu/changelog-cli#2]
I find this behaviour a bit intrusive and asymmetric with the `--create message` command.

**Comment by mathieu** [comment]
Maybe we shouldn't commit but leave the added/removed files in the staging area ?

**Comment by boissonnat** [comment]
Yep exactly.
The arg to automatically commit would be a nice to have (probably available also for the `changelog -c` command).

**Comment by mathieu** [comment]
fixed with release [1.1.0](https://github.com/mathieu/changelog-cli/releases/tag/1.1.0)
